"""Extract Okabe-Ito colour palettes from src/styles.py and write them to
dashboard/src/data/palette.ts so the React dashboard inherits the exact same
hex values used by every Python plot in the project.

Run from anywhere in the repository:
    python dashboard/scripts/extract_palette.py
"""

import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Bootstrap: resolve repository root and add to sys.path so src.styles is
# importable without requiring an installed package.
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
DASHBOARD_DIR = SCRIPT_DIR.parent
REPO_ROOT = DASHBOARD_DIR.parent
sys.path.insert(0, str(REPO_ROOT))

from src.styles import (  # noqa: E402  (import after path fix is intentional)
    ARM_PALETTE,
    COHORT_PALETTE,
    DRIVER_PALETTE,
    OKABE_ITO,
    PHENOTYPE_PALETTE,
    RESPONSE_PALETTE,
)

OUT_PATH = DASHBOARD_DIR / "src" / "data" / "palette.ts"


def _ts_const(name: str, value: object) -> str:
    """Serialise a Python dict or list as a TypeScript 'as const' declaration."""
    return f"export const {name} = {json.dumps(value, indent=2)} as const;"


def _build_lines() -> list[str]:
    return [
        "// AUTO-GENERATED by dashboard/scripts/extract_palette.py",
        "// DO NOT EDIT BY HAND – source of truth is src/styles.py in the repository root.",
        "// Re-run the script whenever src/styles.py changes.",
        "",
        _ts_const("COHORT_PALETTE", COHORT_PALETTE),
        "",
        _ts_const("RESPONSE_PALETTE", RESPONSE_PALETTE),
        "",
        _ts_const("DRIVER_PALETTE", DRIVER_PALETTE),
        "",
        _ts_const("PHENOTYPE_PALETTE", PHENOTYPE_PALETTE),
        "",
        _ts_const("ARM_PALETTE", ARM_PALETTE),
        "",
        _ts_const("OKABE_ITO", list(OKABE_ITO)),
        "",
        "// ---------------------------------------------------------------------------",
        "// Helper functions mirroring get_phenotype_color() and get_cohort_color()",
        "// from src/styles.py – substring-match so long labels (with parenthetical",
        "// detail) resolve correctly, matching the Python behaviour exactly.",
        "// ---------------------------------------------------------------------------",
        "",
        "/** Returns the Okabe-Ito hex colour for a phenotype label.",
        " *  Uses exact & bidirectional substring matching, mirroring get_phenotype_color() in src/styles.py. */",
        "export function getPhenotypeColor(label: string, fallback = \"#37474F\"): string {",
        "  if (!label) return fallback;",
        "  if ((PHENOTYPE_PALETTE as Record<string, string>)[label]) return (PHENOTYPE_PALETTE as Record<string, string>)[label];",
        "  const lower = label.toLowerCase();",
        "  const entry = Object.entries(PHENOTYPE_PALETTE).find(",
        "    ([key]) => lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)",
        "  );",
        "  if (entry) return entry[1];",
        "  if (lower.includes(\"m2\")) return \"#CC79A7\";",
        "  return fallback;",
        "}",
        "",
        "/** Returns the Okabe-Ito hex colour for a cohort name.",
        " *  Uses substring matching, mirroring get_cohort_color() in src/styles.py. */",
        "export function getCohortColor(label: string, fallback = \"#37474F\"): string {",
        "  if (!label) return fallback;",
        "  const lower = label.toLowerCase();",
        "  const entry = Object.entries(COHORT_PALETTE).find(",
        "    ([key]) => lower.includes(key.toLowerCase())",
        "  );",
        "  return entry ? entry[1] : fallback;",
        "}",
        "",
        "/** Returns the Okabe-Ito hex colour for a treatment arm label.",
        " *  Falls back to PHENOTYPE_PALETTE for arm-less labels. */",
        "export function getArmColor(arm: string, fallback = \"#37474F\"): string {",
        "  if (!arm) return fallback;",
        "  const lower = arm.toLowerCase();",
        "  const entry = Object.entries(ARM_PALETTE).find(",
        "    ([key]) => lower.includes(key.toLowerCase())",
        "  );",
        "  return entry ? entry[1] : fallback;",
        "}",
    ]


def main() -> None:
    lines = _build_lines()
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    rel = OUT_PATH.relative_to(REPO_ROOT).as_posix()
    print(f"Wrote {rel}  ({len(lines)} lines, {len(PHENOTYPE_PALETTE)} phenotype entries)")


if __name__ == "__main__":
    main()
