// ---------------------------------------------------------------------------
// The browsable cohort: 421 real TCGA-SKCM patients, each carrying their Q3 ODE
// digital-twin dose-response and (where available) their Q1 ML prediction.
//
// Everything here is generated by `scripts/build_cohort.mjs` into
// public/cohort.json. Nothing is computed at runtime except the Q5 integration.
// ---------------------------------------------------------------------------

export type BrafCall = "V600E" | "WT";
export type NrasCall = "Mutant" | "WT";
export type ResistanceRisk = "low" | "moderate" | "high" | "unknown";

/** The six gene-expression signatures the Q1 models consume. */
export interface Q1Features {
  IFN_gamma: number | null;
  TIS: number | null;
  CYT: number | null;
  CD8_Tcell: number | null;
  IMPRES: number | null;
  PD_L1: number | null;
}

export interface Q1Prediction {
  /** Ensemble P(response to checkpoint blockade), 0-1. */
  pResponse: number;
  perModel: Record<"lr" | "rf" | "xgb" | "svm" | "enet", number | null>;
  features: Q1Features;
  cohort: string;
  /** "ensemble-only" when the source supplied a single score with no per-model
   *  or signature breakdown — the lane then shows the gauge alone. */
  detail?: "ensemble-only" | "full";
}

export interface Q4Flag {
  label: string;
  detail: string;
}

export interface Q4Block {
  resistanceRisk: ResistanceRisk;
  flags: Q4Flag[];
  /** Salvage / reserve targets to hold for progression. */
  reserve: string[];
}

/** One line of therapy: a TCGA treatment type paired with the agent(s) given
 *  under it, e.g. { type: "Targeted Molecular Therapy", agents: ["Vemurafenib"] }.
 *  `agents` is empty when TCGA recorded the type but not a named drug. */
export interface TreatmentLine {
  type: string;
  agents: string[];
}

/** What TCGA recorded this patient as actually having been treated with —
 *  recorded for ~46% of the cohort; TCGA simply has no data for the rest. */
export interface TreatmentHistory {
  recorded: boolean;
  /** Grouped by TREATMENT_TYPE, each with its own named agent(s) — type first,
   *  agent(s) underneath, so a reader doesn't have to guess which drug maps to
   *  which category. */
  lines: TreatmentLine[];
  /** Received a checkpoint inhibitor (ipilimumab / pembrolizumab / nivolumab) —
   *  the anti-PD-1 axis Q3 simulates. */
  checkpointInhibitor: boolean;
  /** Received a BRAF/MEK inhibitor (vemurafenib / dabrafenib / trametinib) —
   *  the BRAFi axis Q3 simulates. */
  targetedTherapy: boolean;
  chemotherapy: boolean;
  radiation: boolean;
}

export interface CohortPatient {
  id: string;
  sampleId: string;

  // --- molecular (real, from the Q3 simulation inputs) ---
  braf: BrafCall;
  nras: NrasCall;
  mapkDriven: boolean;
  /** Raw CD274 (PD-L1) mRNA. */
  pdl1Expr: number;
  /** Raw PDCD1 (PD-1) mRNA. */
  pdcd1Expr: number;
  /** Percentile rank of CD274 across the cohort, 0-100 — the display "PD-L1 %". */
  pdl1Pct: number;
  pdcd1Pct: number;

  // --- clinical (real, from TCGA clin_cleaned.csv) ---
  age: number | null;
  sex: "M" | "F" | null;
  stage: string;
  stageBand: string;
  tmb: number | null;
  tmbPct: number | null;
  osMonths: number | null;
  /** 1 = death observed, 0 = censored. */
  osEvent: number | null;

  // --- Q3 ODE digital twin ---
  /** Tumour burden as % of this patient's own untreated baseline, across the
   *  10-step dose sweep. Null when the twin carries no usable baseline. */
  brafiCurve: number[] | null;
  antipd1Curve: number[] | null;
  brafiBaseline: number;
  antipd1Baseline: number;
  /** False when the ODE settled at a numerically-zero tumour compartment, i.e.
   *  the twin has nothing to say for this patient — this is NOT "no response". */
  brafiInformative: boolean;
  antipd1Informative: boolean;
  brafiReduction: number;
  antipd1Reduction: number;
  /** Percentile of this reduction among informative twins, 0-100. Null when the
   *  twin is uninformative — this is what puts the mechanistic read-out on the
   *  same footing as the statistical one for the agreement comparison. */
  brafiReductionPct: number | null;
  antipd1ReductionPct: number | null;
  brafiOptimalDose: number | null;
  antipd1OptimalDose: number | null;

  // --- Q1 / Q4 ---
  q1: Q1Prediction | null;
  q4: Q4Block;

  // --- treatment actually received (real, from TCGA clin_cleaned.csv) ---
  treatment: TreatmentHistory;

  /** Set only by the what-if explorer. TCGA records no LDH, so the engine
   *  normally infers rapid-control pressure from stage IV; supplying a value
   *  here lets a clinician pose the "what if their LDH were high?" question. */
  ldhOverride?: "Normal" | "Elevated" | "High";
}

// --- Q1 cohort-level validation (the ICI trials, which have real labels) -----

export interface ConfusionStats {
  threshold: number;
  n: number;
  tp: number;
  fp: number;
  tn: number;
  fn: number;
  accuracy: number | null;
  sensitivity: number | null;
  specificity: number | null;
  ppv: number | null;
  npv: number | null;
}

export interface Q1Validation {
  n: number;
  responders: number;
  auc: number | null;
  atHalf: ConfusionStats;
  atTuned: ConfusionStats;
  perModel: { model: string; auc: number }[];
  byCohort: { cohort: string; n: number; responders: number; auc: number | null; meanProb: number }[];
  distribution: { bin: string; lo: number; responders: number; nonResponders: number }[];
  roc: { fpr: number; tpr: number }[];
}

export interface CohortMeta {
  generated: string;
  source: string;
  nQ3: number;
  nQ1Tcga: number;
  doseAxis: number[];
  q1Validation: Q1Validation | null;
  q1Note: string;
}

export interface Cohort {
  meta: CohortMeta;
  patients: CohortPatient[];
}

/** Fetch the pre-built cohort. The only network call the app makes. */
export async function loadCohort(): Promise<Cohort> {
  const res = await fetch(`${import.meta.env.BASE_URL}cohort.json`);
  if (!res.ok) {
    throw new Error(`Could not load cohort.json (${res.status}). Run: node scripts/build_cohort.mjs`);
  }
  return (await res.json()) as Cohort;
}

// --- small shared helpers ---------------------------------------------------

/**
 * Composite of the real checkpoint-axis biomarkers (PD-L1, PD-1, TMB percentiles).
 * This is the statistical immunotherapy read-out we fall back to while the Q1
 * models cannot score the TCGA cohort. It is measured data, not a model output —
 * the UI must label it as a biomarker composite, never as "Q1".
 */
export function biomarkerComposite(p: CohortPatient): number {
  const parts = [p.pdl1Pct, p.pdcd1Pct, p.tmbPct].filter(
    (v): v is number => v !== null && Number.isFinite(v)
  );
  if (!parts.length) return 50;
  return Math.round(parts.reduce((a, b) => a + b, 0) / parts.length);
}

export function pdl1Band(pct: number): "High" | "Intermediate" | "Low" {
  if (pct >= 66) return "High";
  if (pct >= 33) return "Intermediate";
  return "Low";
}
