// AUTO-GENERATED by dashboard/scripts/extract_palette.py
// DO NOT EDIT BY HAND – source of truth is src/styles.py in the repository root.
// Re-run the script whenever src/styles.py changes.

export const COHORT_PALETTE = {
  "Liu 2019": "#0072B2",
  "Hugo 2016": "#E69F00",
  "Riaz 2017": "#CC79A7",
  "TCGA-SKCM": "#37474F",
  "Pooled Trials": "#009E73"
} as const;

export const RESPONSE_PALETTE = {
  "CR/PR": "#009E73",
  "Responder": "#009E73",
  "Response": "#009E73",
  "PD": "#D55E00",
  "Non-responder": "#D55E00",
  "Non-Response": "#D55E00",
  "SD": "#F0E442"
} as const;

export const DRIVER_PALETTE = {
  "BRAF": "#D55E00",
  "NRAS": "#56B4E9",
  "NF1": "#009E73",
  "Triple-WT": "#CC79A7"
} as const;

export const PHENOTYPE_PALETTE = {
  "Immune Hot": "#D55E00",
  "Immune Hot (High TIS & CYT, Inflamed Microenvironment)": "#D55E00",
  "Immune Cold": "#0072B2",
  "Immune Cold (Low TIS & Infiltration, Desert)": "#0072B2",
  "M2-High": "#CC79A7",
  "M2": "#CC79A7",
  "Immunosuppressive M2-High": "#CC79A7",
  "Immunosuppressive M2-High (Depleted T-cells & Stromal Exclusion)": "#CC79A7",
  "M2 Immunosuppressive": "#CC79A7",
  "M2 Immunosuppressive (High M2 Macrophages & CAFs)": "#CC79A7",
  "Mutant-Driven": "#F0E442",
  "Mutant-Driven (NF1 Loss & High Response Subtype)": "#F0E442"
} as const;

export const ARM_PALETTE = {
  "Arm A: Immunotherapy": "#009E73",
  "Arm B: Targeted Therapy": "#E69F00",
  "Arm C: Combination/Reversal": "#CC79A7"
} as const;

export const OKABE_ITO = [
  "#E69F00",
  "#56B4E9",
  "#009E73",
  "#F0E442",
  "#0072B2",
  "#D55E00",
  "#CC79A7",
  "#000000"
] as const;

// ---------------------------------------------------------------------------
// Helper functions mirroring get_phenotype_color() and get_cohort_color()
// from src/styles.py – substring-match so long labels (with parenthetical
// detail) resolve correctly, matching the Python behaviour exactly.
// ---------------------------------------------------------------------------

/** Returns the Okabe-Ito hex colour for a phenotype label.
 *  Uses exact & bidirectional substring matching, mirroring get_phenotype_color() in src/styles.py. */
export function getPhenotypeColor(label: string, fallback = "#37474F"): string {
  if (!label) return fallback;
  if ((PHENOTYPE_PALETTE as Record<string, string>)[label]) return (PHENOTYPE_PALETTE as Record<string, string>)[label];
  const lower = label.toLowerCase();
  const entry = Object.entries(PHENOTYPE_PALETTE).find(
    ([key]) => lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)
  );
  if (entry) return entry[1];
  if (lower.includes("m2")) return "#CC79A7";
  return fallback;
}

/** Returns the Okabe-Ito hex colour for a cohort name.
 *  Uses substring matching, mirroring get_cohort_color() in src/styles.py. */
export function getCohortColor(label: string, fallback = "#37474F"): string {
  if (!label) return fallback;
  const lower = label.toLowerCase();
  const entry = Object.entries(COHORT_PALETTE).find(
    ([key]) => lower.includes(key.toLowerCase())
  );
  return entry ? entry[1] : fallback;
}

/** Returns the Okabe-Ito hex colour for a treatment arm label.
 *  Falls back to PHENOTYPE_PALETTE for arm-less labels. */
export function getArmColor(arm: string, fallback = "#37474F"): string {
  if (!arm) return fallback;
  const lower = arm.toLowerCase();
  const entry = Object.entries(ARM_PALETTE).find(
    ([key]) => lower.includes(key.toLowerCase())
  );
  return entry ? entry[1] : fallback;
}
